### PR TITLE
Cleaned up the repo

### PR DESCRIPTION
**Pull request by mcmonojit**
### Each algorithm/DS has a folder which contains: 
- explanation of the algo/DS. 
- java and/or python code of the algo/DS.

### This pull request solves issue #10

### CODE REVIEW

**Comment by bhavinjawade** [comment]
Hi @mcmonojit ,

Looks good. Please correct links in the readme.md  to point to the correct files (inside directories). Will merge the PR once its done.

Thanks

**Comment by mcmonojit** [comment]
I am pretty new these. I don't know how to edit the links in the readme.md file. Some guidance will be very helpfull.

**Comment by mcmonojit** [comment]
> Hi @mcmonojit ,
> 
> Looks good. Please correct links in the readme.md to point to the correct files (inside directories). Will merge the PR once its done.
> 
> Thanks

Hello @bhavinjawade , I have updated the readme.md file as you have mentioned. Please review my PR.

**Comment by mcmonojit** [comment]
Hello @bhavinjawade , please let me know if there is any issue with my pull request.

**Comment by mcmonojit** [comment]
Hello @bhavinjawade , I am participating in Hacktoberfest 2020. As you know there has been some modifications in the rules. A pull request needs to be labeled as " hacktoberfest-accepted " by the maintainer to be valid. So if this PR has been helpfull could you please add the following label to this PR. 
>> hacktoberfest-accepted

**Pull request merged**
